# Generated by Django 5.0.6 on 2024-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='cycle',
            field=models.CharField(max_length=11),
        ),
    ]
