# Generated by Django 5.0.6 on 2024-07-15 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='career',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.level'),
        ),
    ]
