# Generated by Django 5.0.6 on 2024-07-15 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_level_subject_career_alter_career_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career'),
        ),
    ]
